# Keep the application's pinned firmware URLs identical to the root README.
# This function is also exercised against fixture READMEs by CTest.
function(core_firmware_catalog readme output)
    file(READ "${readme}" contents)
    set(entries "")
    foreach(model IN ITEMS zeptocore ectocore ezeptocore)
        foreach(build IN ITEMS normal lowLatency noOverclocking noOverclockingLowLatency visualizer)
            if(model STREQUAL "zeptocore" AND build MATCHES "^noOverclocking")
                continue()
            endif()
            set(suffix "")
            if(build STREQUAL "lowLatency")
                set(suffix "_low_latency")
            elseif(build STREQUAL "noOverclocking")
                set(suffix "_no_overclocking")
            elseif(build STREQUAL "noOverclockingLowLatency")
                set(suffix "_no_overclocking_low_latency")
            elseif(build STREQUAL "visualizer")
                set(suffix "_visualizer")
            endif()
            set(version "v[0-9]+\\.[0-9]+\\.[0-9]+")
            string(REGEX MATCHALL "https://github\\.com/schollz/_core/releases/download/${version}/${model}_${version}${suffix}\\.uf2" urls "${contents}")
            list(REMOVE_DUPLICATES urls)
            list(LENGTH urls count)
            if(NOT count EQUAL 1)
                message(FATAL_ERROR "Expected exactly one ${model} ${build} UF2 URL in ${readme}; found ${count}. Update its firmware links before building the sample manager.")
            endif()
            list(GET urls 0 url)
            string(REGEX REPLACE ".*/download/([^/]+)/.*" "\\1" tag "${url}")
            set(filename "${model}_${tag}${suffix}.uf2")
            if(NOT url STREQUAL "https://github.com/schollz/_core/releases/download/${tag}/${filename}")
                message(FATAL_ERROR "Firmware release tag and filename disagree: ${url}")
            endif()
            string(APPEND entries "    {FirmwareHardware::${model}, FirmwareBuild::${build}, \"${tag}\", \"${filename}\", \"${url}\"},\n")
        endforeach()
    endforeach()
    file(CONFIGURE OUTPUT "${output}" CONTENT "// Generated from the root README; do not edit.\nstatic const std::vector<FirmwareEntry> firmwareEntries{\n@entries@};\n" @ONLY)
endfunction()
