#!/bin/sh
export GOPATH=$HOME/go
export PATH=$HOME/bin:$PATH:/usr/local/go/bin/:$HOME/go/bin:$HOME/node/bin:$HOME/.cargo/bin
export PATH="$HOME/zig-linux-x86_64-0.11.0:$PATH"
# Check if the merge was an update
if [ "$1" = "0" ]; then  # Ensure this condition works as expected in your context
    echo "Update detected. Running custom command..."
    cd /www/zeptocore && /usr/bin/make core_linux_amd64
    /usr/bin/systemctl restart zns.zeptocore.service
fi

