include("${CORE_SOURCE_DIR}/cmake/FirmwareCatalog.cmake")
file(MAKE_DIRECTORY "${TEST_OUTPUT_DIR}")
file(READ "${CORE_SOURCE_DIR}/../README.md" original)
set(readme "${TEST_OUTPUT_DIR}/README.md")
set(generated "${TEST_OUTPUT_DIR}/catalog.h")
file(WRITE "${readme}" "${original}")
core_firmware_catalog("${readme}" "${generated}")
file(READ "${generated}" header)
string(REGEX MATCHALL "https://github\\.com/schollz/_core/releases/download/[^\"]+" links "${header}")
list(LENGTH links count)
if(NOT count EQUAL 13)
    message(FATAL_ERROR "Expected all 13 README firmware URLs")
endif()
foreach(link IN LISTS links)
    string(FIND "${original}" "${link}" pos)
    if(pos LESS 0)
        message(FATAL_ERROR "Generated URL does not exist in README: ${link}")
    endif()
endforeach()
# Verify version updates regenerate all URLs, without consulting the app version.
string(REGEX REPLACE "v[0-9]+\\.[0-9]+\\.[0-9]+" "v99.1.2" updated "${original}")
file(WRITE "${readme}" "${updated}")
core_firmware_catalog("${readme}" "${generated}")
file(READ "${generated}" header)
if(NOT header MATCHES "ezeptocore_v99.1.2_no_overclocking_low_latency.uf2")
    message(FATAL_ERROR "README firmware version did not regenerate")
endif()
file(WRITE "${TEST_OUTPUT_DIR}/configure.cmake"
    "include(\"${CORE_SOURCE_DIR}/cmake/FirmwareCatalog.cmake\")\ncore_firmware_catalog(\"${readme}\" \"${generated}\")\n")
foreach(problem IN ITEMS missing ambiguous mismatched)
    if(problem STREQUAL "missing")
        string(REPLACE "ezeptocore_v99.1.2_visualizer.uf2" "absent.uf2" bad "${updated}")
    elseif(problem STREQUAL "ambiguous")
        set(bad "${updated}\nhttps://github.com/schollz/_core/releases/download/v99.2.0/ezeptocore_v99.2.0_visualizer.uf2")
    else()
        string(REPLACE "ezeptocore_v99.1.2_visualizer.uf2" "ezeptocore_v98.1.2_visualizer.uf2" bad "${updated}")
    endif()
    file(WRITE "${readme}" "${bad}")
    execute_process(COMMAND "${CMAKE_COMMAND}" -P "${TEST_OUTPUT_DIR}/configure.cmake"
                    RESULT_VARIABLE result OUTPUT_QUIET ERROR_VARIABLE error)
    if(result EQUAL 0 OR NOT error MATCHES "(Expected exactly one|release tag and filename disagree)")
        message(FATAL_ERROR "${problem} catalog must fail with an actionable error: ${error}")
    endif()
endforeach()
message(STATUS "Firmware catalog: all 13 links, version regeneration, missing/ambiguous/mismatched links passed")
